### ISSUE TITLE
Cannot invoke "String.indexOf(String)" because "line" is null when using JDK 16

### ISSUE THREAD

**Issue by Zeon8** [consulo/consulo-java#90]
Hello, I created hello world project with JDK 16 and when I tried to run I got an error.
Here is consule.log:
```
[ 360758]   WARN - Compiler.CompilerParsingThread - Cannot invoke "String.indexOf(String)" because "line" is null 
java.lang.NullPointerException: Cannot invoke "String.indexOf(String)" because "line" is null
	at com.intellij.compiler.impl.javaCompiler.javac.JavacOutputParser.addJavacPattern(JavacOutputParser.java:233) ~[AnnotationProcessingCompiler.class:?]
	at com.intellij.compiler.impl.javaCompiler.javac.JavacOutputParser.processMessageLine(JavacOutputParser.java:80) ~[AnnotationProcessingCompiler.class:?]
	at com.intellij.compiler.impl.javaCompiler.CompilerParsingThread.run(CompilerParsingThread.java:101) [AnnotationProcessingCompiler.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[ 360869]   INFO - lij.compiler.impl.CompilerUtil - 	COMPILATION FINISHED; Errors: 1; warnings: 0 took 467 ms: 0 min 0sec 
```
Consulo:
  version = 2021.9
  build number = 2974
  build date = September 24, 2021

**Comment by VISTALL** [comment]
Hello. I will check after my vacation. One/two weeks.

**Comment by VISTALL** [comment]
Hello. There new experimental compiler was added some time ago. You can test it with enabled option here

![](https://klikr.org/bce895e3bcfe42bc455125326f52.png)

But need switch to nightly, but there was bug in it, and was fixed today
